apiVersion: v1
kind: Service
metadata:
  name: makeline-service
spec:
  selector:
    app: makeline-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3070
    - name: api
      protocol: TCP
      port: 3070
      targetPort: 3070
  type: ClusterIP 